package globals.rules

global java.lang.Integer count
global java.util.List list
//global 只在当前规则中生效
rule "global_1"
enabled false
when
then
    count += 10;
    System.out.println("count = " + count);
end

rule "global_2"
enabled false
when
then
     System.out.println("count = " + count);
end

rule "global_3"
enabled false
when
then
    System.out.println(list.get(0));
    System.out.println("list length is " + list.size());
end

